Improvements on added UserManager toggles
GrapheneOS/platform_packages_apps_Settings pull request #120
Opened 2022-08-23 14:43 UTC by quh4gko8

2022-08-23 14:56 UTC, quh4gko8 commented
has been tested on emulator and found to have same logs as if it's logged out from added logout option

the said logs refer to [this one](https://github.com/GrapheneOS/os-issue-tracker/issues/258#issuecomment-684677223)

2023-06-06 10:53 UTC, muhomorr commented
Need to factor out code from `onPreferenceChange()`, it's the same as `DISALLOW_INSTALL_APPS` and `DISALLOW_INSTALL_UNKNOWN_SOURCES` restrictions.

2023-06-15 12:49 UTC, muhomorr commented on src/com/android/settings/users/UserDetailsSettings.java
> +            mDefaultGuestRestrictions.putBoolean(userManagerKey, !enabled);
I think negation should be done in the callers of this method, not in the method itself.

2023-06-16 10:02 UTC, quh4gko8 commented
This PR now also changes the description to match AOSP guidelines to add settings, as well as to expose "allow to install apps" toggle to Guest users, where it's allowed by default in AOSP.

2023-06-16 11:16 UTC, muhomorr requested changes

2023-06-16 11:16 UTC, muhomorr commented on res/values/strings.xml
> +    <string name="user_disallow_install_apps">Allow installing apps</string>
String ids have to be updated too (ie `user_allow_install_apps`)

2023-06-16 11:16 UTC, muhomorr commented on res/values/strings.xml
> +    <string name="user_disallow_run_in_background">Allow running on background</string>
"on background" -> "in background"

2023-06-16 16:25 UTC, muhomorr approved these changes

2023-06-16 19:51 UTC, merged