improvements to UserManager restriction settings
GrapheneOS/platform_packages_apps_Settings pull request #182
Opened 2023-07-21 13:21 UTC by quh4gko8

Changes from previous UserManager settings implementation:

- Move run in background settings right below switch user settings.
- Unify app install settings into three options for non-guest users, and two for guest users. This has also been moved right above the install available apps settings.
- Helper class for fetching and setting UserManager restrictions exposed to users.
- Remove incorrect caching of default guest' user manager restrictions.

2023-07-21 20:35 UTC, matchboxbananasynergy commented on res/values/strings.xml
> +    <string name="user_app_install_updates_enabled_known_sources_desc">Enable app installs and updates from known sources only</string>
```suggestion
    <string name="user_app_install_updates_enabled_known_sources_desc">Enable app installs and updates from known sources only</string>
```

Is "known sources" the correct way to say this? If that is the canonical way to phrase it, no worries, but it feels like that could be vague for some play. Play Store is "known" (people know about it). It's "unknown" to the OS, though. I fear that it won't be clear enough, whereas third-party might be more clear, although I'm not entirely sure if that phrasing won't be misinterpreted as well.

2023-07-24 02:16 UTC, robcle commented on res/values/strings.xml
> +    <string name="user_app_install_updates_enabled_known_sources_desc">Enable app installs and updates from known sources only</string>
Exactly, when the third party app installation permission is turned off in owner, the permission toggle in secondary profile for play store app installation is greyed out. Either the wording in the owner permission should include a explanation that the play store is included in the toggle, or the feature should allow the play store to install apps if the "Allow installing apps" is checked in owner + the "allow installing apps from third party sources" is unchecked. Its a tad confusing to new users. IMO if a user wants the play store in a secondary user, then they are trusting the play store, but they may not be trusting Aurora or f-droid for example. So the feature should reflect that.

2023-07-24 17:48 UTC, muhomorr requested changes

2023-07-24 17:48 UTC, muhomorr commented on src/com/android/settings/users/UserRestrictions.java
> +    boolean isSet(String userManagerKey) {
Better name would be `key`, or `restrictionKey`

2023-07-24 17:48 UTC, muhomorr commented on src/com/android/settings/users/UserRestrictions.java
> +    UserRestrictions(UserManager userManager, UserInfo userInfo) {
Constructor should be placed after field declarations.

2023-07-24 17:48 UTC, muhomorr commented on src/com/android/settings/users/UserInstallUpdateSettings.java
> +        candidates.add(0, new CandidateInfoExtra(ctx.getString(R.string.user_app_install_enabled),
It's better for readability to add items in the order they appear (also more efficient, though it doesn't matter in this case).

Pseudo-code:
if not guest
  add(INSTALL_ENABLED)

add(FIRST_PARTY_ENABLED)
add(DISABLED)

2023-07-24 17:48 UTC, muhomorr commented on src/com/android/settings/users/UserDetailsSettings.java
> +        userRestrictions.set(UserManager.DISALLOW_SMS, mUserInfo.isGuest() || !enabled);
Upstream comment 
`// SMS is always disabled for guest`
should be kept

2023-07-24 17:48 UTC, muhomorr commented on src/com/android/settings/users/UserDetailsSettings.java
> +        if (Boolean.TRUE.equals(newValue)) {
Missing `if (preference == mPhonePref) {` check

2023-07-24 17:48 UTC, muhomorr commented on res/xml/user_details_settings.xml
> +    <com.android.settingslib.RestrictedPreference
It's better to place this setting right before `app_copying` setting, they are both related to app installation.

2023-07-24 17:48 UTC, muhomorr commented on res/values/strings.xml
> +    <!-- Title of preference to enable app installs and updates [CHAR LIMIT=40] -->
Move these strings to strings_ext.xml to avoid rebase conflicts.

2023-07-25 14:54 UTC, muhomorr requested changes

2023-07-25 14:54 UTC, muhomorr commented on src/com/android/settings/users/UserAppsInstallSettings.java
> +            candidates.add(0, new CandidateInfoExtra(ctx.getString(R.string.user_app_install_enabled),
First argument (`0`) is not needed

2023-07-25 14:54 UTC, muhomorr commented on src/com/android/settings/users/UserAppsInstallSettings.java
> +            return false;
What's the purpose of this code block?

2023-07-25 14:54 UTC, muhomorr commented on src/com/android/settings/users/UserAppsInstallSettings.java
> +    static void launch(Preference preference, int userId) {
Missing empty line after field declarations

2023-07-26 15:42 UTC, merged