Configuration UI for installing available apps, toggling cross profile clipboard access, delay for locking storage when stopping a user for private profile
GrapheneOS/platform_packages_apps_Settings pull request #315
Opened 2024-12-27 10:52 UTC by quh4gko8

2024-12-27 10:53 UTC, quh4gko8 commented
Depends on: https://github.com/GrapheneOS/platform_frameworks_base/pull/89

2024-12-30 20:40 UTC, muhomorr requested changes

2024-12-30 20:40 UTC, muhomorr commented on src/com/android/settings/users/AppCopyFragmentHelperExt.java
> +            pi = pm.getPackageInfo(pkgName, flags);
This is an expensive call, calling it for each package will slow down the Install available apps screen. This filtering should be handled in addCurrentUsersApps() or removeSecondUsersApp(), ApplicationInfos are fetched there already.

2024-12-31 16:20 UTC, quh4gko8 commented
Now also requires https://github.com/GrapheneOS/platform_frameworks_base/pull/98

2025-03-13 23:13 UTC, closed without merging

2025-03-14 00:44 UTC, thestinger commented
Needs to be reopened against 15-qpr2.